//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DongXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DongXe()
        {
            this.Xes = new HashSet<Xe>();
        }

        public int ID { get; set; }
        [Display(Name = "Car name")]
        [Required(ErrorMessage = "It's not empty!!")]
        public string Ten { get; set; }
        [Display(Name = "Price")]
        [Required(ErrorMessage = "It's not empty!!")]
        public decimal Gia { get; set; }
        [Display(Name = "Seat")]
        [Required(ErrorMessage = "It's not empty!!")]
        public int SoCho { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Xe> Xes { get; set; }
    }
}
