//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HopDongThueXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDongThueXe()
        {
            this.SoXes = new HashSet<SoXe>();
        }

        public int ID { get; set; }
        public int IDKH { get; set; }
        public int IDXe { get; set; }
        [Display(Name = "National ID")]
        public string CMND { get; set; }
        [Display(Name = "Rental days")]
        public int SoNgayThue { get; set; }
        [Display(Name = "Pick-up date")]
        public string TGGiaoXe { get; set; }
        [Display(Name = "Drop-off date")]
        public string TGTraXe { get; set; }
        [Display(Name = "Pick-up location")]
        public string DiaDiemGiaoXe { get; set; }
        [Display(Name = "Deposit")]
        public decimal ThanhToanTruoc { get; set; }
        [Display(Name = "Rest")]
        public decimal ConLai { get; set; }
        [Display(Name = "Expected amount")]
        public decimal TienDuKien { get; set; }
        public int IDTrangThaiHD { get; set; }

        public virtual TrangThaiHopDong TrangThaiHopDong { get; set; }
        public virtual User User { get; set; }
        public virtual Xe Xe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoXe> SoXes { get; set; }
    }
}
