//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SoDatXe
    {
        public int ID { get; set; }
        public int IDKH { get; set; }
        public int IDXe { get; set; }
        [Display(Name = "Book date")]
        public string NgayDat { get; set; }

        public virtual User User { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
