//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SoXe
    {
        public int ID { get; set; }
        public int IDHD { get; set; }
        [Display(Name = "Real drop-off date")]
        [Required(ErrorMessage = "It's not empty!!")]
        public string TGTraXeTT { get; set; }
        [Display(Name = "Extra payment")]
        [Required(ErrorMessage = "It's not empty!!")]
        public decimal SoTienTraThem { get; set; }
        public Nullable<decimal> SoTienCanTra { get; set; }

        public virtual HopDongThueXe HopDongThueXe { get; set; }
    }
}
