//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamSo
    {
        public decimal TyLeTraThemKhiQuaNgay { get; set; }
        public decimal TyLeTraThemKhiTonHaiXe { get; set; }
    }
}
