//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Xe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Xe()
        {
            this.HopDongThueXes = new HashSet<HopDongThueXe>();
            this.SoDatXes = new HashSet<SoDatXe>();
        }

        public int ID { get; set; }
        [Display(Name = "Image")]
        [Required(ErrorMessage = "It's not empty!!")]
        public string HinhAnh { get; set; }
        [Display(Name = "Status")]
        [Required(ErrorMessage = "It's not empty!!")]
        public bool TinhTrang { get; set; }
        [Display(Name = "License plate")]
        [Required(ErrorMessage = "It's not empty!!")]
        public string BienSo { get; set; }
        public int IDDongXe { get; set; }
        public int IDHangXe { get; set; }
        [Display(Name = "Year of manufacture")]
        [Required(ErrorMessage = "It's not empty!!")]
        public int NamSX { get; set; }
        [Display(Name = "Price ratio")]
        [Required(ErrorMessage = "It's not empty!!")]
        public decimal TyLeGia { get; set; }
        [Display(Name = "Note")]
        [Required(ErrorMessage = "It's not empty!!")]
        public string GhiChu { get; set; }

        public virtual DongXe DongXe { get; set; }
        public virtual HangXe HangXe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDongThueXe> HopDongThueXes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoDatXe> SoDatXes { get; set; }
    }
}
